13781 back integration
os-nsu/ostest-runner pull request #4
Opened 2024-12-09 13:27 UTC by MierQQ

Добавил поддержку выбора тестов
когда лабы == "" или их нет в ответе запускаются все тесты
когда тесты == [] запускаются все тесты
когда используются вместе, используется их пересечение
Выбор лаб при помощи списка протестировал при помощи mock_server, как на локальном проверить не понял

2024-12-10 08:34 UTC, borodun requested changes

2024-12-10 08:34 UTC, borodun commented on runner.py
> +	parser.add_argument("--timeout", type=int, default=600)
Нужно написать доку про все флаги раннера в README.md

2024-12-10 08:34 UTC, borodun commented on mock_server/test_backend.py
>  		task["laboratoryNumber"] = 1
Кажется, laboratoryNumber может быть массивом лаб. По крайней мере наши тесты это позволяют делать. 

Не завязываемся тут на бек. Без разници что от него придет: число, массив или пустота, но мы внутри работаем с laboratoryNumber как массивом.

2024-12-10 08:34 UTC, borodun commented on README.md
>  ### Start mock backend
flask запускает сервер на 5000 порту. Надо добавить в README пример запуска ранера с мок бекендом на 5000 порту

2024-12-10 08:34 UTC, borodun commented on modules/network.py
> +			logging.error(f"refresh token error, setting reseting auth, return code:\n{response.status_code}")
Заметил опечатки в сообщениях:
setting reseting auth ->  resetting auth ??
runned -> ran
due to signal recieve - > due to stop signal
relogining and resending results -> logging again and ... ??
recieved -> received

2024-12-10 08:34 UTC, borodun commented on modules/run_test.py
> +			connectedTestsStringPattern = connectedTests[0]
connectedTestsStringPattern нужно обернуть в кавычки, тк это один большой аргумент для флага -k. А то падает с такой ошибкой:
```
ERROR: file or directory not found: or
```

2024-12-10 08:34 UTC, borodun commented on mock_server/test_backend.py
> +		task["connectedTests"] = ["test_static_library_compilation", "test_plugin_compilation"]
Надо бы выбрать тесты, которые не зависят от других. А то они не запускаются пока зависимые тесты не пройдут:

```
SKIPPED [1] ../../../venv/lib/python3.12/site-packages/pytest_dependency.py:101: test_static_library_compilation depends on tests/lab1/test_file_structure.py::test_files_exist[Makefile]
SKIPPED [1] ../../../venv/lib/python3.12/site-packages/pytest_dependency.py:101: test_plugin_compilation depends on tests/lab1/test_build.py::test_dynamic_library_compilation
```

2024-12-10 08:34 UTC, borodun commented on modules/network.py
> +			logging.error(f"refresh token error, setting reseting auth, return code:\n{response.status_code}")
Почему статус код на новой строке печается? Надо бы на той же

2024-12-10 08:34 UTC, borodun commented on modules/run_test.py
>  		is_good, out, err = self.__start_with_signal_watch(args, cwd, clean_up, "tests run")
Внутри __start_with_signal_watch я бы добавил дебажно логирование команды, которая исолняется. Что-то такое:

```
logging.debug(f"Executing cmd: \"{' '.join(args)}\"")
```

2024-12-10 08:34 UTC, borodun commented on mock_server/test_backend.py
> +		task["connectedTests"] = ["test_static_library_compilation", "test_plugin_compilation"]
Как понимаю, из-за этого мок беку не приходит description тестов:

```json
'testResults': [{'name': 'lab1.test_build::test_static_library_compilation', 'isPassed': True, 'description': '', 'duration': 0, 'memoryUsed': 1317}, {'name': 'lab1.test_build::test_plugin_compilation', 'isPassed': True, 'description': '', 'duration': 0, 'memoryUsed': 1120}]
```

Надо бы поправить парсер xml)

2024-12-10 19:20 UTC, MierQQ commented on runner.py
> +	parser.add_argument("--timeout", type=int, default=600)
сделал

2024-12-10 19:20 UTC, MierQQ commented on mock_server/test_backend.py
>  		task["laboratoryNumber"] = 1
сделал

2024-12-10 19:20 UTC, MierQQ commented on runner.py
> +	parser.add_argument("--timeout", type=int, default=600)
сделал

2024-12-10 19:20 UTC, MierQQ commented on README.md
>  ### Start mock backend
сделал

2024-12-10 19:21 UTC, MierQQ commented on modules/network.py
> +			logging.error(f"refresh token error, setting reseting auth, return code:\n{response.status_code}")
поправил

2024-12-10 19:24 UTC, MierQQ commented on modules/run_test.py
> +			connectedTestsStringPattern = connectedTests[0]
С кавычками не работает, без них работает
```
ERROR: file or directory not found: or
```
такую проблему не встречал, мб возможно передается в connectedTestsStringPattern 
```
 or 
```
поэтому ругается, переписал, чтобы такого не было

2024-12-10 19:24 UTC, MierQQ commented on mock_server/test_backend.py
> +		task["connectedTests"] = ["test_static_library_compilation", "test_plugin_compilation"]
Поправил для скипнутых тестов

2024-12-10 19:25 UTC, MierQQ commented on modules/network.py
> +			logging.error(f"refresh token error, setting reseting auth, return code:\n{response.status_code}")
исправил, убрал переводы на новые строки из логов

2024-12-10 19:25 UTC, MierQQ commented on modules/run_test.py
>  		is_good, out, err = self.__start_with_signal_watch(args, cwd, clean_up, "tests run")
добавил

2024-12-10 19:27 UTC, MierQQ commented
сделал таймаут 0.9 от таймаута процесса, чтобы тесты имели возможность закончится перед посылкой сигнала

2024-12-12 09:57 UTC, borodun requested changes

2024-12-12 09:57 UTC, borodun commented on README.md
> +Argumets:
Надо бы добавить - перед каждым параметром, а том markdown всэ то в одну строку конвертирует: https://github.com/os-nsu/ostest-runner/tree/13781_back_integration?tab=readme-ov-file#logger

2024-12-12 10:04 UTC, merged